# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        swift: [ '5.7', '5.8', '5.9' ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Swift
        uses: fwal/setup-swift@v1
        with:
          swift-version: '${{ matrix.swift }}'
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v