# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Swift
      uses: fwal/setup-swift@v1
      with:
        swift-version: '5.9'
    - name: Build
      run: swift build -v
    # - name: Run tests
    #   run: swift test -v
    # Temporarily disabling the test run on GitHub Actions due to a compatibility issue with Swift 5.9.
    # Local tests are running fine. We are looking into resolving this issue.